# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-taishan"
BBFILE_PATTERN_meta-taishan = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-taishan = "7"

LAYERDEPENDS_meta-taishan = "core"
LAYERSERIES_COMPAT_meta-taishan = "scarthgap"

INIT_MANAGER = "systemd"
IMAGE_INSTALL:append = " \
    swupdate \
    swupdate-www \
    swupdate-tools \
    u-boot-fw-utils \
    e2fsprogs \
    parted \
"
PACKAGECONFIG:append:pn-swupdate = " json mongoose"
RPI_USE_U_BOOT = "1"
ENABLE_UART = "1"

# WKS_FILE = "sdimage-raspberrypi-taishan.wks"
IMAGE_FSTYPES = "wic.gz wic.bmap ext4.gz wic.bz2"
SWUPDATE_BOOTLOADER = "u-boot"