# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-taishan"
BBFILE_PATTERN_meta-taishan = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-taishan = "90"

LAYERDEPENDS_meta-taishan = "core"
LAYERSERIES_COMPAT_meta-taishan = "scarthgap"

PACKAGECONFIG:append = " json"
DEPENDS += "json-c"
IMAGE_ROOTFS_SIZE = "2048000"

IMAGE_FSTYPES += "wic wic.bz2"
# WKS_FILE = "raspberrypi4-64-dual-root-data.wks"
PREFERRED_VERSION_linux-raspberrypi = "6.12.%"

IMAGE_INSTALL:append = " \
                    packagegroup-app \
                    packagegroup-network \
                    packagegroup-swupdate \
                    packagegroup-debug \
                     "

IMAGE_INSTALL:append = " \
                    tcpdump \
                    openssh \
                    openssh-sftp-server\
                    network-config \
                    swupdate \
                    swupdate-www \
                    lighttpd \
                     "