header:
  version: 14
repos:

  poky:
    url: git@github.com:xiaofeng232/poky.git
    path: layers/poky
    commit: e6bfeed8f3e72c577820e3d01f7d697c4d3fc5d4
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: git@github.com:xiaofeng232/meta-openembedded.git
    path: layers/meta-openembedded
    commit: 89a01c3d9ad1f8fce6aeb4dd0e694cfa28d42099
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-perl:
      meta-filesystems:

bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  shared_dirs: |
    DL_DIR ?= "/work/build/downloads"
    SSTATE_DIR ?= "/work/build/sstate-cache"
  diskmon: |
    BB_DISKMON_DIRS ??= "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"