# Copyright (c) 2025-2026 Taishan Control System. All rights reserved.
#
# Description:
#   A simple Hello World application for demonstration purposes
#
# Authors:
#   Lin Xiaofeng <xiaofeng.lin1@foxmail.com>
#
# Changelog:
#   0.0.1 (2026-01-22):
#     - Initial implementation
#
# License: Closed - Internal Use Only

require conf/distro/poky.conf

DISTRO = "taishan"
DISTRO_NAME = "Taishan Control Linux"
DISTRO_VERSION = "5.0.14"

POKY_INIT_MANAGER = "systemd"
INIT_MANAGER = "systemd"

DISTRO_FEATURES:remove = "opengl wayland vulkan ptest"
DISTRO_FEATURES:append = " systemd usbhost serial"

LICENSE_FLAGS_ACCEPTED:append = " synaptics-killswitch"

PREFERRED_VERSION_linux-yocto ?= "6.6%"